receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource:
    attributes:
      - key: appdynamics.controller.account
        action: upsert
        value: "curie202304050848454"
      - key: appdynamics.controller.host
        action: upsert
        value: "curie202304050848454.saas.appdynamics.com"
      - key: appdynamics.controller.port
        action: upsert
        value: 443
  batch:
#    timeout: 30s
#    send_batch_size: 90

exporters:
  logging:
    loglevel: debug
#  jaeger:
#    endpoint: host.docker.internal:14251
#    tls:
#      insecure: true
  otlphttp:
    endpoint: "https://fra-sls-agent-api.saas.appdynamics.com"
    headers: { "x-api-key": "92ff50292b0765bb0cb8479b419d9786947beb72edef30c6c1aaa927107a37e6" }

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ resource, batch ]
      exporters: [ logging, otlphttp ]
#      exporters: [ logging, otlphttp, jaeger ]
#    metrics:
#      receivers: [ otlp ]
#      processors: [ resource, batch ]
#      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      processors: [ resource, batch ]
      exporters: [ logging, otlphttp ]