receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource:
    attributes:
      - key: appdynamics.controller.account
        action: upsert
        value: "earlywarning-preprod"
      - key: appdynamics.controller.host
        action: upsert
        value: "earlywarning-preprod.saas.appdynamics.com"
      - key: appdynamics.controller.port
        action: upsert
        value: 443
  batch:
    timeout: 30s
    send_batch_size: 90

exporters:
#  otlp:
#    endpoint: host.docker.internal:4317
#    tls:
#      insecure: true
  logging:
    loglevel: debug
  otlphttp:
    endpoint: "https://pdx-sls-agent-api.saas.appdynamics.com"
    headers: {"x-api-key": "5ca40d5bf541df42af3dc20bc680cc6812d02e54382d59be183ff918bd8013d5"}
  jaeger:
    endpoint: host.docker.internal:14251
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp, logging, jaeger ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp, logging ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp, logging ]