receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: host.docker.internal:4317
    tls:
      insecure: true
  logging:
    loglevel: debug
  jaeger:
    endpoint: host.docker.internal:14251
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, logging, jaeger ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, logging ]
    metrics/internal:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, logging ]
    logs/signalfx:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, logging ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, logging ]