# config file version
apiVersion: 1

datasources:
  - name: "Prometheus"
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    editable: true
    isDefault: false
  - name: Jaeger
    uid: webstore-traces
    type: jaeger
    url: http://jaeger-query:16686/jaeger/ui
    editable: true
    isDefault: false
