version: "3.8"

services:
  els:
    image: elasticsearch:7.17.22
    restart: on-failure
    container_name: els
    hostname: els
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./eslog:/usr/share/elasticsearch/logs
  kibana:
    image: kibana:7.17.22
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: "kibana"
      ELASTICSEARCH_HOSTS: "http://els:9200"
    depends_on:
      - els
  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    ports:
      - "14250:14250"
      - "14267:14267"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    depends_on:
      - els
    container_name: jaeger-collector
    hostname: jaeger-collector
    restart: unless-stopped
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: ["--es.num-shards=1", "--es.num-replicas=0", "--es.server-urls=http://els:9200"]
  otel-collector:
    image: otel/opentelemetry-collector:0.72.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    restart: unless-stopped
    container_name: otel-collector
    depends_on:
      - els
      - jaeger-collector
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
     - ZOOKEEPER_CLIENT_PORT=2181
     - ZOOKEEPER_TICK_TIME=2000
    restart: on-failure
    volumes:
      - ./zoo:/var/lib/zookeeper
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://152.70.149.143:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper
    volumes:
      - ./broker:/var/lib/kafka
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    ports:
      - 16686:16686
      - 16687:16687
    depends_on:
      - els
      - jaeger-collector
      - prometheus
    restart: unless-stopped
    container_name: jaeger-query
    environment:
      SPAN_STORAGE_TYPE: "elasticsearch"
      METRICS_STORAGE_TYPE: "prometheus"
    command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://els:9200", "--prometheus.server-url=http://prometheus:9090", "--prometheus.query.support-spanmetrics-connector=true"]
