receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: "applicationMetricsReader"
          scrape_interval: 5s
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: [ "q6c470c96n.ews.int:8080" ]
              labels:
                application: 'OrderApp'
            - targets: [ "q6c470c96n.ews.int:8081" ]
              labels:
                application: 'OrderHistoryApp'
            - targets: [ "q6c470c96n.ews.int:8082" ]
              labels:
                application: 'ShipmentApp'
            - targets: [ "q6c470c96n.ews.int:8083" ]
              labels:
                application: 'GreetingApp'

processors:
  batch:
#    timeout: 30s
#    send_batch_size: 90

exporters:
  logging:
    loglevel: debug
  otlp/jaeger:
    endpoint: jaeger-collector:14250
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
  otlp/elasticsearch:
    endpoint: els:9200
    tls:
      insecure: true
#  prometheus:
#    endpoint: "0.0.0.0:8889"
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, otlp/jaeger ]
    metrics:
      receivers: [ otlp, prometheus ]
      processors: [ batch ]
      exporters: [ logging, otlphttp/prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging , otlp/elasticsearch ]