receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
#    timeout: 30s
#    send_batch_size: 90

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-collector:14250
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
#  prometheus:
#    endpoint: "0.0.0.0:8889"
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, jaeger ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, otlphttp/prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]