apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-rest
  name: kafka-rest-service
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: kafka-rest-port
    port: 8082
    nodePort: 30082
    targetPort: 8082
  selector:
    app: kafka-rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-rest
  name: kafka-rest
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      hostname: kafka-rest
      containers:
      - env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_REST_HOST_NAME
          value: kafka-rest
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        image: confluentinc/cp-kafka-rest:latest
        imagePullPolicy: IfNotPresent
        name: kafka-rest
        ports:
        - containerPort: 8082
